### ISSUE TITLE
歌单API更换后，自定义播放列表的时候，PC端播放正常，移动端播放失败

### ISSUE THREAD

**Issue by olllooo** [yusixian/cos_blogs#12]
歌单API更换后,自定义播放列表的时候，PC端播放正常，**移动端播放失败**。
目前只测试了iphone的safari。
自定义列表设置如下
```
   - title: 测试
     list:
      - name: "山茶花不懂白玫瑰"
        url: "https://olllooo.github.io/media/山茶花不懂白玫瑰.m4a"
        artist: "aaa"
        cover: "bbb"
        lrc: "歌词"
```
